#
# Module manifest for module 'ConvertFrom-GoodReads'
#
# Generated by: mootix1313
#
# Generated on: 29 November 2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ConvertFrom-GoodReads'

# Version number of this module.
ModuleVersion = '0.0.2'

# ID used to uniquely identify this module
GUID = '61078192-0405-48f4-824f-543d251407d3'

# Author of this module
Author = 'mootix1313'

# Copyright statement for this module
Copyright = '(c) mootix1313. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A module to assist converting a Goodreads library export file (csv) into individual markdown files, for each book within the CSV file, to be incorporated into an Obsidian Vault.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
  'Libs/Import-Assemblies.psm1'
)

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
  'Libs/Import-Assemblies.psm1',
  'Libs/booklog-class.psm1',
  'Libs/logging.psm1',
  'Libs/manipulate-data.psm1',
  'Libs/search-functions.psm1'
)

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
  'ConvertFrom-GoodReads',
  'Import-GoodreadsLibrary'
  'Get-FlattenedObject',
  'Get-FormattedObject',
  'New-LogName',
  'New-BookTags',
  'Search-Gbook',
  'Search-Openlib',
  'Merge-BookData',
  'New-BookMetadata',
  'New-BookLogObject',
  'Build-BookLog',
  'Start-GoodreadsLogging'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @('ConvertFrom-GoodReads')

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
#AliasesToExport = @()

# List of all modules packaged with this module
ModuleList = @(
  'Libs/booklog-class.psm1',
  'Libs/logging.psm1',
  'Libs/manipulate-data.psm1',
  'Libs/search-functions.psm1',
  'Libs/PoShLog/2.2.0/PoShLog.psm1',
  'Libs/PoShLog.Enrichers/1.0.0/PoShLog.Enrichers.psm1',
  'Libs/powershell-yaml/0.4.7/powershell-yaml.psm1'
)

# List of all files packaged with this module
FileList = @(
  './ConvertFrom-GoodReads.psd1',
  './ConvertFrom-GoodReads.psm1',
  './Libs/booklog-class.psm1',
  './Libs/logging.psm1',
  './Libs/manipulate-data.psm1',
  './Libs/search-functions.psm1',
  './Libs/PoShLog.Enrichers/1.0.0/LICENSE',
  './Libs/PoShLog.Enrichers/1.0.0/PoShLog.Enrichers.psd1',
  './Libs/PoShLog.Enrichers/1.0.0/PoShLog.Enrichers.psm1',
  './Libs/PoShLog.Enrichers/1.0.0/lib/Microsoft.CSharp.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/Serilog.Enrichers.Environment.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/Serilog.Enrichers.Process.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/Serilog.Enrichers.Thread.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/Serilog.Exceptions.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/System.Collections.NonGeneric.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/System.Dynamic.Runtime.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/System.IO.FileSystem.Primitives.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/System.Linq.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/System.Linq.Expressions.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/System.ObjectModel.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/System.Reflection.Emit.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/System.Reflection.Emit.ILGeneration.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/System.Reflection.Emit.Lightweight.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/System.Reflection.TypeExtensions.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/System.Text.RegularExpressions.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/System.Threading.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/System.Threading.Thread.dll',
  './Libs/PoShLog.Enrichers/1.0.0/lib/System.Threading.ThreadPool.dll',
  './Libs/PoShLog.Enrichers/1.0.0/functions/enrichers/Add-EnrichWithEnvironment.ps1',
  './Libs/PoShLog.Enrichers/1.0.0/functions/enrichers/Add-EnrichWithExceptionDetails.ps1',
  './Libs/PoShLog.Enrichers/1.0.0/functions/enrichers/Add-EnrichWithProcessId.ps1',
  './Libs/PoShLog.Enrichers/1.0.0/functions/enrichers/Add-EnrichWithProcessName.ps1',
  './Libs/PoShLog/2.1.1/PoShLog.psd1',
  './Libs/PoShLog/2.1.1/PoShLog.psm1',
  './Libs/PoShLog/2.1.1/README.md',
  './Libs/PoShLog/2.1.1/lib/PoShLog.Core.dll',
  './Libs/PoShLog/2.1.1/lib/Serilog.dll',
  './Libs/PoShLog/2.1.1/lib/Serilog.Sinks.Console.dll',
  './Libs/PoShLog/2.1.1/lib/Serilog.Sinks.File.dll',
  './Libs/PoShLog/2.1.1/lib/System.IO.FileSystem.Primitives.dll',
  './Libs/PoShLog/2.1.1/functions/Write-DebugLog.ps1',
  './Libs/PoShLog/2.1.1/functions/Write-ErrorLog.ps1',
  './Libs/PoShLog/2.1.1/functions/Write-FatalLog.ps1',
  './Libs/PoShLog/2.1.1/functions/Write-InfoLog.ps1',
  './Libs/PoShLog/2.1.1/functions/Write-InformationLog.ps1',
  './Libs/PoShLog/2.1.1/functions/Write-VerboseLog.ps1',
  './Libs/PoShLog/2.1.1/functions/Write-WarningLog.ps1',
  './Libs/PoShLog/2.1.1/functions/enrichers/Add-EnrichFromLogContext.ps1',
  './Libs/PoShLog/2.1.1/functions/enrichers/Add-EnrichWithErrorRecord.ps1',
  './Libs/PoShLog/2.1.1/functions/enrichers/Add-EnrichWithProperty.ps1',
  './Libs/PoShLog/2.1.1/functions/core/Close-Logger.ps1',
  './Libs/PoShLog/2.1.1/functions/core/New-LevelSwitch.ps1',
  './Libs/PoShLog/2.1.1/functions/core/New-Logger.ps1',
  './Libs/PoShLog/2.1.1/functions/core/Set-LevelSwitch.ps1',
  './Libs/PoShLog/2.1.1/functions/core/Set-Logger.ps1',
  './Libs/PoShLog/2.1.1/functions/core/Set-MinimumLevel.ps1',
  './Libs/PoShLog/2.1.1/functions/core/Start-Logger.ps1',
  './Libs/PoShLog/2.1.1/functions/sinks/Add-SinkConsole.ps1',
  './Libs/PoShLog/2.1.1/functions/sinks/Add-SinkFile.ps1',
  './Libs/PoShLog/2.1.1/functions/sinks/Add-SinkPowerShell.ps1',
  './Libs/PoShLog/2.1.1/functions/internal/Add-PackageTypes.ps1',
  './Libs/PoShLog/2.1.1/functions/internal/Get-FormattedMessage.ps1',
  './Libs/PoShLog/2.1.1/functions/internal/Set-LogLevelToPreference.ps1',
  './Libs/PoShLog/2.1.1/functions/internal/Test-Logger.ps1',
  './Libs/PoShLog/2.1.1/functions/internal/Test-PsCore.ps1',
  './Libs/PoShLog/2.1.1/functions/internal/Write/Write-Log.ps1',
  './Libs/PoShLog/2.1.1/functions/internal/Write/Write-SinkPowerShell.ps1',
  './Libs/PoShLog/2.1.1/functions/formatters/Get-JsonFormatter.ps1',
  './Libs/PoShLog/2.1.1/functions/helpers/Convert-LogFunctions.ps1',
  './Libs/PoShLog/2.2.0/PoShLog.psd1',
  './Libs/PoShLog/2.2.0/PoShLog.psm1',
  './Libs/PoShLog/2.2.0/README.md',
  './Libs/PoShLog/2.2.0/lib/PoShLog.Core.dll',
  './Libs/PoShLog/2.2.0/lib/PoShLog.Core.xml',
  './Libs/PoShLog/2.2.0/lib/Serilog.dll',
  './Libs/PoShLog/2.2.0/lib/Serilog.Sinks.Console.dll',
  './Libs/PoShLog/2.2.0/lib/Serilog.Sinks.File.dll',
  './Libs/PoShLog/2.2.0/lib/System.IO.FileSystem.Primitives.dll',
  './Libs/PoShLog/2.2.0/functions/Write-DebugLog.ps1',
  './Libs/PoShLog/2.2.0/functions/Write-ErrorLog.ps1',
  './Libs/PoShLog/2.2.0/functions/Write-FatalLog.ps1',
  './Libs/PoShLog/2.2.0/functions/Write-InfoLog.ps1',
  './Libs/PoShLog/2.2.0/functions/Write-InformationLog.ps1',
  './Libs/PoShLog/2.2.0/functions/Write-VerboseLog.ps1',
  './Libs/PoShLog/2.2.0/functions/Write-WarningLog.ps1',
  './Libs/PoShLog/2.2.0/functions/enrichers/Add-EnrichFromLogContext.ps1',
  './Libs/PoShLog/2.2.0/functions/enrichers/Add-EnrichWithErrorRecord.ps1',
  './Libs/PoShLog/2.2.0/functions/enrichers/Add-EnrichWithProperty.ps1',
  './Libs/PoShLog/2.2.0/functions/core/Close-Logger.ps1',
  './Libs/PoShLog/2.2.0/functions/core/Get-Logger.ps1',
  './Libs/PoShLog/2.2.0/functions/core/New-LevelSwitch.ps1',
  './Libs/PoShLog/2.2.0/functions/core/New-Logger.ps1',
  './Libs/PoShLog/2.2.0/functions/core/Set-LevelSwitch.ps1',
  './Libs/PoShLog/2.2.0/functions/core/Set-Logger.ps1',
  './Libs/PoShLog/2.2.0/functions/core/Set-MinimumLevel.ps1',
  './Libs/PoShLog/2.2.0/functions/core/Start-Logger.ps1',
  './Libs/PoShLog/2.2.0/functions/sinks/Add-SinkConsole.ps1',
  './Libs/PoShLog/2.2.0/functions/sinks/Add-SinkFile.ps1',
  './Libs/PoShLog/2.2.0/functions/sinks/Add-SinkLogger.ps1',
  './Libs/PoShLog/2.2.0/functions/sinks/Add-SinkPowerShell.ps1',
  './Libs/PoShLog/2.2.0/functions/debugging/Disable-SelfLog.ps1',
  './Libs/PoShLog/2.2.0/functions/debugging/Enable-SelfLog.ps1',
  './Libs/PoShLog/2.2.0/functions/internal/Get-FormattedMessage.ps1',
  './Libs/PoShLog/2.2.0/functions/internal/Set-LogLevelToPreference.ps1',
  './Libs/PoShLog/2.2.0/functions/internal/Test-Logger.ps1',
  './Libs/PoShLog/2.2.0/functions/internal/Write/Write-Log.ps1',
  './Libs/PoShLog/2.2.0/functions/internal/Write/Write-SinkPowerShell.ps1',
  './Libs/PoShLog/2.2.0/functions/formatters/Get-JsonFormatter.ps1',
  './Libs/PoShLog/2.2.0/functions/utils/Get-CurrentLogFiles.ps1',
  './Libs/PoShLog/2.2.0/functions/utils/Set-DefaultMessageFormatter.ps1',
  './Libs/PoShLog/2.2.0/functions/helpers/Add-PackageTypes.ps1',
  './Libs/PoShLog/2.2.0/functions/helpers/Convert-LogFunctions.ps1',
  './Libs/PoShLog/2.2.0/functions/helpers/Test-PsCore.ps1',
  './Libs/powershell-yaml/0.4.7/LICENSE',
  './Libs/powershell-yaml/0.4.7/Load-Assemblies.ps1',
  './Libs/powershell-yaml/0.4.7/powershell-yaml.psd1',
  './Libs/powershell-yaml/0.4.7/powershell-yaml.psm1',
  './Libs/powershell-yaml/0.4.7/README.md',
  './Libs/powershell-yaml/0.4.7/lib/net35/LICENSE-libyaml',
  './Libs/powershell-yaml/0.4.7/lib/net35/LICENSE.txt',
  './Libs/powershell-yaml/0.4.7/lib/net35/YamlDotNet.dll',
  './Libs/powershell-yaml/0.4.7/lib/net35/YamlDotNet.xml',
  './Libs/powershell-yaml/0.4.7/lib/netstandard2.1/LICENSE-libyaml',
  './Libs/powershell-yaml/0.4.7/lib/netstandard2.1/LICENSE.txt',
  './Libs/powershell-yaml/0.4.7/lib/netstandard2.1/YamlDotNet.deps.json',
  './Libs/powershell-yaml/0.4.7/lib/netstandard2.1/YamlDotNet.dll',
  './Libs/powershell-yaml/0.4.7/lib/netstandard2.1/YamlDotNet.xml',
  './Libs/powershell-yaml/0.4.7/lib/net45/LICENSE-libyaml',
  './Libs/powershell-yaml/0.4.7/lib/net45/LICENSE.txt',
  './Libs/powershell-yaml/0.4.7/lib/net45/System.ComponentModel.Primitives.dll',
  './Libs/powershell-yaml/0.4.7/lib/net45/System.ComponentModel.TypeConverter.dll',
  './Libs/powershell-yaml/0.4.7/lib/net45/YamlDotNet.dll',
  './Libs/powershell-yaml/0.4.7/lib/net45/YamlDotNet.xml'  
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

  PSData = @{

      # Tags applied to this module. These help with module discovery in online galleries.
      Tags = @(
        'obsidian',
        'goodreads'
      )

      # A URL to the license for this module.
      LicenseUri = 'https://raw.githubusercontent.com/Mootix1313/ConvertFrom-GoodReads/main/LICENSE'

      # A URL to the main website for this project.
      ProjectUri = 'https://raw.githubusercontent.com/Mootix1313/ConvertFrom-GoodReads'

      # A URL to an icon representing this module.
      # IconUri = ''

      # ReleaseNotes of this module
      # ReleaseNotes = ''

      # Prerelease string of this module
      # Prerelease = ''

      # Flag to indicate whether the module requires explicit user acceptance for install/update/save
      #RequireLicenseAcceptance = $true

      # External dependent modules of this module
      ExternalModuleDependencies = @(
        'Libs/PoShLog/2.2.0/PoShLog.psm1',
        'Libs/PoShLog.Enrichers/1.0.0/PoShLog.Enrichers.psm1',
        'Libs/powershell-yaml/0.4.7/powershell-yaml.psm1'
      )

  } # End of PSData hashtable

} # End of PrivateData hashtable

}